---
- hosts: all
  tasks:
  - name: install nginx and ensure it is at the latest version
    apt: 
        name: nginx
	state: latest
  - name: start nginx service
    service:
        name: nginx
        state: started
